title: My Resume
author: Sherry Freitas
email: tbd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the resume for Sherry Freitas.  Last updated October 2018.

# social links
github_username:  sfreitas9

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
